baseURL = 'http://benoitboidin.com'
languageCode = 'fr-fr'
title = 'Portfolio de Benoît Boidin'
theme = 'hextra'
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files